# Generated by Django 4.0.2 on 2022-02-10 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coupon_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
