# Generated by Django 4.0.2 on 2022-02-15 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_vendorprofile_address'),
        ('app', '0006_cancelreason_order_add_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterestaurants',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='cancelreason',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='favoriterestaurants',
            name='restaurant',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.vendorprofile'),
            preserve_default=False,
        ),
    ]
