# Generated by Django 4.0.2 on 2022-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_favoriterestaurants_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
