# Generated by Django 4.0.2 on 2022-03-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paymentmethod'),
        ),
    ]
