# Generated by Django 4.0.2 on 2022-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app.CartItems'),
        ),
    ]
