# Generated by Django 4.0.2 on 2022-03-06 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_order_apartment_no_order_flat_no_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterestaurants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
