# Generated by Django 4.0.2 on 2022-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_favoriterestaurants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
