# Generated by Django 4.0.2 on 2022-03-26 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_transferwalletbalance_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
