# Generated by Django 4.0.2 on 2022-02-10 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Permission',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255, unique=True)),
                ('permissions', models.ManyToManyField(to='Dashboard.Permission')),
            ],
            options={
                'verbose_name': 'Role',
                'ordering': ['-id'],
            },
        ),
    ]
