# Generated by Django 4.0.2 on 2022-02-10 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_driverprofile_total_earning_driverprofile_total_paid'),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Closed', max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.driverprofile')),
            ],
            options={
                'verbose_name': 'Driver',
                'ordering': ['-id'],
            },
        ),
    ]
