# Generated by Django 4.0.2 on 2022-02-17 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_role_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sit_fav_icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('support_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(choices=[('$', '$'), ('৳', '৳'), ('€', '€')], default='$', max_length=255)),
                ('contact_less_delivery', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('store_kilo', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_kilo', models.PositiveIntegerField(blank=True, null=True)),
                ('max_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('multiple_delivery', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True)),
                ('otp_verification', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('copyright_year', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_url', models.CharField(blank=True, max_length=255, null=True)),
                ('google_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('google_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_client', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_post', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_fee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('store_comission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver_comission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_methods', models.ManyToManyField(to='Dashboard.PaymentMethods')),
                ('payout_methods', models.ManyToManyField(to='Dashboard.PayoutMethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
