# Generated by Django 4.0.2 on 2022-02-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_paymentmethods_payoutmethod_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='email_post',
            new_name='email_port',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='sit_fav_icon',
            new_name='site_fav_icon',
        ),
    ]
