# Generated by Django 4.0.2 on 2022-03-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='booking_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Distance Wise', 'Distance Wise')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='driver_comission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_comission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
