# Generated by Django 4.0.2 on 2022-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recently_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
