# Generated by Django 4.0.2 on 2022-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0004_rename_cateogory_img_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recently_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
