# Generated by Django 4.0.2 on 2022-02-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ['-id'], 'verbose_name': 'Vendor Profile'},
        ),
    ]
