# Generated by Django 4.0.2 on 2022-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_vendorprofile_total_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
