# Generated by Django 4.0.2 on 2022-02-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_paymentmethods_payoutmethod_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='vendor',
        ),
    ]
