# Generated by Django 4.0.2 on 2022-02-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_sitesettings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='payout_methods',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentMethods',
        ),
        migrations.DeleteModel(
            name='PayoutMethod',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
