# Generated by Django 4.0.2 on 2022-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_sitesettings_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_longtitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
