# Generated by Django 4.0.2 on 2022-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_vendorprofile_vendor_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_penalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_penalized',
            field=models.BooleanField(default=False),
        ),
    ]
