# Generated by Django 4.0.2 on 2022-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_driverprofile_is_penalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='nid_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tin_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='trade_license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
